### PR TITLE
Adjust styles of panes

### PR DESCRIPTION
**Pull request by Atlas16A**
image

Adjusts the styles of the panes, change clearcolor of viewport camera to utilize theme.

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by tim-blackbird** [comment]
We already look too much like Blender, copying their colors too is a bad idea :sweat_smile:

**Comment by Atlas16A** [comment]
> We already look too much like Blender, copying their colors too is a bad idea :sweat_smile: 

I was mainly doing it to get the color contrast balance, previously my eyes kinda were hurting are the inverted color balance

**Comment by tim-blackbird** [comment]
That's fair, I have no problem with changing the colors at all, but looking like Blender is a bad look for us.
We should find something nice that sets us apart.

**Comment by Atlas16A** [comment]
That is the plan, I'm just not worried about looking like blender for how early we are rn.

**Pull request merged**
