### PR TITLE
Change bevy dependency to be main branch of bevy & Reserve components for Pane Layout system

### PR DESCRIPTION
**Pull request by Atlas16A**

### CODE REVIEW

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
I think I'm okay to swap to bevy main for now (LWIM is the only immediately planned third party dependency) but we need to pick a specific arbitrary commit to avoid uncontrolled breakage.

**Comment by bushrat011899** [comment]
> I think I'm okay to swap to bevy main for now (LWIM is the only immediately planned third party dependency) but we need to pick a specific arbitrary commit to avoid uncontrolled breakage.

I'm not familiar with how easy it would be to setup, but perhaps a something like [dependabot](https://docs.github.com/en/code-security/dependabot) could be used to automate _trying_ to keep the editor aligned with `bevy/main`?

**Comment by Atlas16A** [comment]
I mustve done something wrong cause github is automatticly making my commits combine into this PR

**Comment by Atlas16A** [comment]
Ill make a new PR and seperate these commits

**Pull request closed without merging**
