### PR TITLE
Asset browser V1

### PR DESCRIPTION
**Pull request by hcabel**
Image

# Features
1. Reflect the assets directory on disk
2. Auto sync if any change is made to the asset directory 
3. TopBar show the current path
4. Any segment of the TopBar path is clickable to go back to the desired directory
5. Folder assets can be clicked to step into them
6. I've made 2 icon in figma to get things started

I've decided to go this way because from my experience I've realize people tends to prefer asset browser that are synced with the disk.

# Testing
To test it, you can bind it to the editor UI like so:
1. Go to the `bevy_editor` crate
2. Add `bevy_asset_browser.workspace = true` to `Cargo.toml` 
3. Open `src/ui.rs`
4. Import `use bevy_asset_browser::{AssetBrowserNode, AssetBrowserPlugin, AssetBrowserSet};`
5. In the plugin build function: configure_sets `AssetBrowserSet` and add_plugins `AssetBrowserPlugin`
6. then add `parent.spawn(AssetBrowserNode);` to the UI

# Notes
- I don't know where the game assets will be stored, so for now I've target the assets folder in the root directory
- To sync the asset browser to any external changes, I'm using the folder's metadata's modified time. I've stored the last modified value in a resources but I'm not sure it belong (since it has no purpose externally), is that ok?
- Please check for typos or weird phrasing, I'm not a native English speaker. (you've probably already noticed that 😆) trying my best
- I'm not using `bevy_pane_layout`, I haven't seen any other crate used it yet, so I'm not sure how to use it or if it's even finished

# Disclaimer
I'm here to help, if anything's ain't to your liking I'll be happy to change it. (My concern atm is that it might what you've envisioned)
I'm not a Rust nor a Bevy expert, I'll do my research but if I didn't use a rust/bevy feature, it's probably that I didn't knew it existed and I'll be happy to rework my code accordingly.

### CODE REVIEW

**Review by mockersf — DISMISSED** [review]
you should not use the file system but the asset reader from Bevy to access assets

**Comment by Atlas16A** [comment]
You should be using svgs.

**Comment by Atlas16A** [comment]
`bevy_pane_layout` isn't finished but it's in a state where you can target it for testing.

I'll make a PR later to show how to utilize it for testing on.

**Comment by hcabel** [comment]
> You should be using svgs.

That's what I tried at first, but it seems that [bevy doesn't support SVG loading](https://github.com/bevyengine/bevy/issues/1139) yet

Don't know what's the external crate policy is, but I wasn't able to make [bevy_svg](https://github.com/Weasy666/bevy_svg/) work anyway.
A mismatched between the bevy rev that the editor is using and the latest bevy release bevy_svg is using (something about `plugin::sealed::Plugins<_>` not being implemented)

**Comment by Atlas16A** [comment]
> > You should be using svgs.
> 
> That's what I tried at first, but it seems that [bevy doesn't support SVG loading](https://github.com/bevyengine/bevy/issues/1139) yet
> 
> Don't know what's the external crate policy is, but I wasn't able to make [bevy_svg](https://github.com/Weasy666/bevy_svg/) work anyway.
> A mismatched between the bevy rev that the editor is using and the latest bevy release bevy_svg is using (something about `plugin::sealed::Plugins<_>` not being implemented)

Ah right damn. Should probably upstream that soon, alright just add the svg sources to the PR but keep using the PNG till we can swap over to the svgs.

**Comment by MiniaczQ** [comment]
Bit offtopic question, what's the license for those icon assets?

**Comment by hcabel** [comment]
> Bit offtopic question, what's the license for those icon assets?

Idk, I've just spend couple minutes making them in Figma. I'm happy to give every right to the bevy foundation
I imagine we're going to replace soon enough, either to make better ones or to use ones from an icon library

**Review by Atlas16A — APPROVED** [review]

**Comment by hcabel** [comment]
Just fixed the latest conflict 👍

**Review by Atlas16A — APPROVED** [review]

**Pull request merged**
