### PR TITLE
Make clippy happy

### LINKED ISSUE #18: CI checks aren't being run in the merge queue correctly
See https://github.com/bevyengine/bevy_editor_prototypes/queue/main

This works fine on the main Bevy repo, so maybe there's a config problem. We can also just turn off the merge queue, although it is convenient.

### PR DESCRIPTION
**Pull request by janhohenheim**
Resolves #18 by definition when merged, haha

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
This time for real: I swear branch protection is set up correctly this time.

**Comment by alice-i-cecile** [comment]
Failed sucessfully. TBH, I think you should make an empty lib.rs for now to get this to pass (and maybe remove this dummy test?).

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
Clippy is happy, but CI is failing.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
You're trying to run `DefaultPlugins` in your test :)

**Comment by janhohenheim** [comment]
I thought just disabling `WinitPlugin` was enough to have it headless 🤔 
I tend to avoid `MinimalPlugins` because it does not play well with glTF loading.

**Pull request merged**
